version: 2
jobs:
  test_ml_model:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Running ml_model tests
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r packages/ml_model/requirements.txt
            py.test -vv packages/ml_model/tests

  test_ml_api:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Running ml_api tests
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r packages/ml_api/requirements.txt
            py.test -vv packages/ml_api/tests
  train_and_upload_ml_model:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Setup environment
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r packages/ml_model/requirements.txt
      - run:
          name: Publish model in Gemfury
          command: |
            . venv/bin/activate
            chmod +x ./scripts/publish_model.sh
            PYTHONPATH=./packages/ml_model python3 packages/ml_model/ml_model/train_pipeline.py
            ./scripts/publish_model.sh ./packages/ml_model/
workflows:
  version: 2
  test-all:
    jobs:
      - test_ml_model
      - test_ml_api
      - train_and_upload_ml_model
      - test_ml_api:
          requires:
            - train_and_upload_ml_model
