version: 2
jobs:
  test_ml_model:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Running tests
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r packages/ml_model/requirements.txt
            py.test -vv packages/ml_model/tests

workflows:
  version: 2
  test-all:
    jobs:
      - test_ml_model
